services:
  mariadb:
    image: mariadb:latest
    container_name: monolith-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: monolith
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
