services:
  mariadb:
    image: mariadb:latest
    container_name: order-db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: order_db
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
    ports:
      - "3307:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
